### ISSUE TITLE
[Refactor] Disunite application child

### ISSUE THREAD

**Issue by Lightieey** [pre-Q/preQ_Server#80]
## 🪄  Feature Description
현재 preq 폴더 밑에 있던 application child 폴더 분리하기

## 📝  To-do
- [ ] application child 폴더 분리 (controller, service, dto, repository)
- [ ] 지원서 저장할 때 지원서 생성하고 예상질문 생성 한번에 같이하는거 어떻게 할지 고민
- [ ] coverletter -> application child 이름 다 안바뀐거 수정
- [ ]
